version: "3.9"
services:

  fake-exporter:
    build: .
    container_name: fake-exporter
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"



# services:
#   fake-exporter:
#     build:
#       context: .
#     container_name: fake-exporter
#     volumes:
#       - ./weapons.csv:/data/weapons.csv:ro
#     ports:
#       - "5000:5000"

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#     ports:
#       - "9090:9090"
#     depends_on:
#       - fake-exporter

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     depends_on:
#       - prometheus
