# global:
#   scrape_interval: 5s
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fake-exporter"
    static_configs:
      - targets: ["fake-exporter:5000"]

# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: 'fake'
#     static_configs:
#       - targets: ['fake-exporter:5000']
